### PR TITLE
Media queries

### LINKED ISSUE #3: Break points
- [ ] Assign two break points.
- [ ] Make sure the text fields, photos, and buttons can handle the mid points between them

### PR DESCRIPTION
**Pull request by stacyp2006**
###### What does this PR do?  
- Adds media queries for responsiveness. 
- Adds sass to media queries. 

###### Where should the reviewer start?  
- Styles.css

###### How should this be manually tested?  
- Via the responsiveness tool in Chrome dev tools

###### Any background context you want to provide?  
- line item 1

###### What are the relevant tickets?  
- closes #3

### CODE REVIEW

**Comment by timkeresey** [comment]
I think this is a very thorough use of sass in the media queries

**Review by nathanielmillard — APPROVED** [review]
Honestly these seem like really thorough break points. 
Glad to see we were able to get things so much more responsive, and stay true to the orignal projects visual. 
I think we could easily say this is an evolved and fleshed out version of our orignal project, and not just an entriely new site with similar functionality.

**Review by nathanielmillard — APPROVED** [review]
Looking good!
Glad to have checked on a few lines before merging.

**Review by timkeresey — COMMENTED** [review]
I think this is a very thorough use of sass in the media queries

**Pull request merged**
